export const keyActions: Record<string, string> = {
  key_home: 'Home',
  key_end: 'End',
  key_page_up: 'Page_Up',
  key_page_down: 'Page_Down',
  key_left: 'Left',
  key_right: 'Right',
  key_up: 'Up',
  key_down: 'Down',
  key_enter: 'Return',
  key_escape: 'Escape',
  key_space: 'space',
  key_tab: 'Tab',
};
export const builtin: Record<string, string> = {
  folder_back: 'Back',
  page_next: 'Next Page',
  page_previous: 'Previous Page',
  page_first: 'First Page',
  page_last: 'Last Page',
  page_global_next: 'Next Page',
  page_global_previous: 'Previous Page',
  page_global_first: 'First Page',
  page_global_last: 'Last Page',
  none: 'Unassigned',
  terminal: 'Open Terminal',
  browser: 'Open Default Browser',
  files: 'Open Files',
  mic_mute: 'Mute Microphone',
  media_play_pause: 'Play / Pause',
  screenshot: 'Screenshot',
  lock: 'Lock Screen',
  workspace_prev: 'Previous Workspace',
  workspace_next: 'Next Workspace',
  overview: 'Workspace Overview',
  volume_down: 'Volume Down',
  volume_up: 'Volume Up',
  volume_mute: 'Mute Output',
  mic_down: 'Microphone Down',
  mic_up: 'Microphone Up',
  lights_toggle: 'Toggle Key Lights',
  lights_brightness_down: 'Key Lights Dimmer',
  lights_brightness_up: 'Key Lights Brighter',
  lights_warmer: 'Key Lights Warmer',
  lights_cooler: 'Key Lights Cooler',
  voxtype_push_to_talk: 'VOXtype Push-to-talk',
};

// Encoder turns repeat on each detent; offer adjustments and navigation steps.
const dialTurnActions = new Set([
  'none',
  'volume_down',
  'volume_up',
  'mic_down',
  'mic_up',
  'lights_brightness_down',
  'lights_brightness_up',
  'lights_warmer',
  'lights_cooler',
  'workspace_prev',
  'workspace_next',
  'page_next',
  'page_previous',
  'page_global_next',
  'page_global_previous',
  'key_left',
  'key_right',
  'key_up',
  'key_down',
  'key_page_up',
  'key_page_down',
  'key_home',
  'key_end',
  'key_tab',
]);

export function actionControls(action: string): string[] {
  return ['button', 'dialPress', ...(dialTurnActions.has(action) ? ['dialTurn'] : [])];
}
